@startuml
title 类

abstract class Abstract
interface Interface {
    +method1()
}
package com.plantuml {
    Abstract <|-- Class02:inherit
    Class02 *-- Class03:contains
    Class03 o-- Class04:aggregation
    Class04 --|> Interface:inherit

    Class01 : func()
    Class01 : void setString(String str)
    Class01 : String getString()
}

class Dummy {
    -field1
    #field2
    ~method1()
    +method2()
}
note right of Dummy
    "可访问性"
    "-  private"
    "#  protected"
    "~ package private"
    "+  public"
end note

class Dummy2 {
    {static} String id
    {abstract} void methods()
}
note bottom of Dummy2
    修饰符{static}或者{abstract}
end note

Dummy2 -> Dummy:link
note on link #blue:Dummy link Dummy2

@enduml